version: 1.2
<<<<<<< HEAD
tools:
  - name: megalodon
    subclass: WDL
    primaryDescriptorPath: /megalodon.wdl
    testParameterFiles:
        - /megalodonsampleinput.json
    authors:
        - name: Mark Soliman
          email: msoliman@ds.dfci.harvard.edu
=======
workflows:
   - name: dorado_basecall
     subclass: WDL
     primaryDescriptorPath: /dorado_basecall.wdl
>>>>>>> d5dc079e91a2a134663ed0bb87da93e02714662c
